### ISSUE TITLE
Should lists with no children be loaded as null or empty lists? What are everyone's thoughts?

### ISSUE THREAD

**Issue by ghost** [Stuart-campbell/RushOrm#56]
Hey,
Why is an empty child list null? Wouldn't it be more useful (e.g. when processing the children with foreach) when an empty child list would be just an empty list?

Thanks in advance

**Comment by Stuart-campbell** [comment]
Hi,

I did think about this at the time and my thoughts where it would be a bit strange to save a null list and it not be null when loaded. Although on the other hand if you save an empty list you will get null back.

The final decision to not set it was simple as it means one less object allocation as I was on the fence otherwise.

I would be reluctant to change it on 1.1* of the library as that could be a breaking change for some people.

I'll leave it as an open issue as if a few more people agree with you it could be updated.

Thanks

**Comment by Stuart-campbell** [comment]
Just had a thought to resolve your issue.

If you define all you lists like

    @RushList(classType = Rush.class)
    public List<Rush> objects = new ArrayList<>();

They will never load as null.

Thanks
