### ISSUE TITLE
relations

### ISSUE THREAD

**Issue by emdete** [Stuart-campbell/RushOrm#76]
hi,

[normally i am not interested in how a ORM is filling the database as long as it works. when i saw severe performance issues in storing quite simple data i started to look into it and have some concerns]

how would a typical 1:n relationship modelled in RushORM object? i tried:

 - having a list in the one object with member of the other class and

 - having a member of the first class in the other class

in a typical RDB design the list is filled by a FK stored in the other table.

it seems that RushORM creates two additional tables and uses joins when reading the n-table. the different Ks are in the statement, i see huge sql statements which seem to mention all Ks of the list objects on the where clause. this is for many small rows very space consuming and finally: slow.

is there any way to speed this up and come nearer to a RDB design?

**Comment by emdete** [comment]
btw: RushORM does a `SELECT * ...` which is considered "bad style", why is that?

**Comment by ufik** [comment]
This is very true, it's sad such a basic behaviour is not implemented. Beside that library looks nice so far, especially I like automatic migration (well done), but without this basic things it's useless :/ Any thoughts about this @Stuart-campbell ?

**Comment by Stuart-campbell** [comment]
Hi,

I'm not sure what is missing? Are you having a noticeable performance issue?

Thanks

**Comment by ufik** [comment]
Well it's not about performance, but more about design of database. It's really not necessary to solve one-to-many problem with additional table, it would be enough to add one column with foreign key inside reference table. You know what I mean? It's just cleaner solution.

**Comment by Stuart-campbell** [comment]
I really don't think you understand how hard the problem is.

When looping through each class to create the tables you are suggesting that every child needs to have a FK of it's parent without any knowlage of if or how many parents it has. I know possible but from my expreence of dealing with recursion it has a huge number of edge cases. This would also make migration harder as due to SQLite's limited supports of ALTER TABLE FK would break done like this.

Also this change would carry no backwards compatibility.

Most other ORM do use FK as you have suggestion and as a result do not support lists so require worse Java code to get the same result.
 
I would agree a cleaner database but worse in every other way.

**Comment by ufik** [comment]
Well it seems we are talking about something different, because I am talking about one-to-many relation and FK is on many side, so every children has just one parent at the same time (not really get that about recursion).

I won't argue about problems with migration, but everything should be solvable in some way.

**Comment by Stuart-campbell** [comment]
Two situation where this breaks.

Class A owns a list of Class B, Class B owns 1 Class A.

If done by FK you have to make sure the bottom of the tree is saved first, but there may not be a bottom due to recursion?

Second multiple instances of Class A own a list of Class B with instances of Class B in more than one list. Class B now has multiple parents from the same field.
